name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: make tests
